name: schedule-deployment

env:
  documentation: 'https://github.com/indexdata/reservoir-scripts/blob/main/js/README.md#workflow-schedule-deployment'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Deployment action'
        required: true
        default: 'add'
        type: choice
        options:
          - 'add'
          - 'remove'
      deployments:
        description: 'List of matchers, e.g. goldrush2024,isxn'
        required: true
        type: string

jobs:
  schedule-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Show documentation
        run: |
          echo "Documentation: ${{ env.documentation }}" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Fail if attempt dispatch on default branch
        if: github.ref_name == github.event.repository.default_branch
        run: |
          echo "The workflow_dispatch is only available for non-default branches." | tee -a "$GITHUB_STEP_SUMMARY"
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.5"
          enable-cache: false

      - name: Set up uv Python
        run: |
          uv python install 3.13

      - name: Verify inputs
        id: verify-inputs
        env:
          DEPLOYMENTS: ${{ inputs.deployments }}
        shell: bash
        run: |
          IFS=', ' read -r -a deployments <<< "${DEPLOYMENTS//[[:blank:]]/}"
          # declare -p deployments
          declare -a errors
          declare -a schedules
          for matcher in "${deployments[@]}"; do
            echo "matcher=${matcher}"
            if ! [ -d "js/matchers/${matcher}" ]; then
              errors+=("The matcher '${matcher}' is not found.")
              continue
            fi
            sha=$(git rev-parse HEAD)
            schedules+=("${matcher}:${sha}")
          done
          if [ ${#errors[@]} -gt 0 ]; then
            printf "ERROR: %s\n" "${errors[@]}"
            exit 1
          else
            schedule=$(printf "%s," "${schedules[@]}" | sed s/,$//)
            echo "schedule=$schedule" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: Show schedule summary
        run: |
          echo "schedule: ${{ inputs.action }}: ${{ steps.verify-inputs.outputs.schedule }}" >> "$GITHUB_STEP_SUMMARY"

      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          # FIXME: actionlint complains about client-id so use deprecated app-id (See actionlint #648 #669)
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: indexdata
          repositories: ${{ secrets.REPO_NAME_GITOPS }}
          permission-contents: write

      - name: Checkout GitOps repository
        uses: actions/checkout@v7
        with:
          repository: indexdata/${{ secrets.REPO_NAME_GITOPS }}
          path: ${{ secrets.REPO_NAME_GITOPS }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Generate data files
        env:
          ACTION: ${{ inputs.action }}
          SCHEDULE: ${{ steps.verify-inputs.outputs.schedule }}
          DIR_OUTPUT: ${{ secrets.REPO_NAME_GITOPS }}
          JOB_ID: ${{ github.run_number }}
        run: uv run .github/workflows/scripts/schedule_deployments.py -l info

      - name: Show recent schedule
        run: tail -5 ${{ secrets.REPO_NAME_GITOPS }}/log/schedule-deployments.jsonl

      - name: Commit git changes and push
        run: |
          cd ${{ secrets.REPO_NAME_GITOPS }}
          ls -R
          git config --global user.name "github-actions-reservoir-scripts"
          git config --global user.email "github-actions-reservoir-scripts@indexdata.com"
#          git add .
#          git status
#          git commit -m "Apply schedule deployments"
#          echo "Do git push ..."
#          git push
