name: schedule-deployment

env:
  documentation: 'https://github.com/indexdata/reservoir-scripts/blob/main/js/README.md#workflow-schedule-deployment'
  namespace: minitex-matchers

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Deployment action'
        required: true
        default: 'add'
        type: choice
        options:
          - 'add'
          - 'remove'
      deployments:
        # description: 'List of matchers, e.g. goldrush2024,isxn'
        description: 'The matcher, e.g. isxn'
        required: true
        type: string

jobs:
  schedule-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Show documentation
        run: |
          echo "Documentation: ${{ env.documentation }}" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: Fail if attempt dispatch on default branch
        if: github.ref_name == github.event.repository.default_branch
        run: |
          echo "The workflow_dispatch is only available for non-default branches." | tee -a "$GITHUB_STEP_SUMMARY"
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "0.12.5"
          enable-cache: false

      - name: Set up uv Python
        run: |
          uv python install 3.13

      - name: Verify inputs
        id: verify-inputs
        env:
          DEPLOYMENTS: ${{ inputs.deployments }}
        shell: bash
        run: |
          IFS=', ' read -r -a deployments <<< "${DEPLOYMENTS//[[:blank:]]/}"
          # declare -p deployments
          declare -a errors
          declare -a schedules
          for matcher in "${deployments[@]}"; do
            echo "matcher=${matcher}"
            if ! [ -d "js/matchers/${matcher}" ]; then
              errors+=("The matcher '${matcher}' is not found.")
              continue
            fi
            sha=$(git rev-parse HEAD)
            schedules+=("${matcher}:${sha}")
          done
          if [ ${#errors[@]} -gt 0 ]; then
            printf "ERROR: %s\n" "${errors[@]}"
            exit 1
          else
            schedule=$(printf "%s," "${schedules[@]}" | sed s/,$//)
            echo "schedule=$schedule" | tee -a "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          # FIXME: actionlint complains about client-id so use deprecated app-id (See actionlint #648 #669)
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: indexdata
          repositories: ${{ secrets.REPO_NAME_GITOPS }}
          permission-contents: write

      - name: Checkout GitOps repository
        uses: actions/checkout@v7
        with:
          repository: indexdata/${{ secrets.REPO_NAME_GITOPS }}
          path: ${{ secrets.REPO_NAME_GITOPS }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Configure pool descriptor and log entry
        env:
          ACTION: ${{ inputs.action }}
          SCHEDULE: ${{ steps.verify-inputs.outputs.schedule }}
          BRANCH_NAME: ${{ github.ref_name }}
          DIR_OUTPUT: ${{ secrets.REPO_NAME_GITOPS }}
          JOB_ID: ${{ github.run_number }}
        run: uv run .github/workflows/scripts/schedule_deployments.py -l info

      - name: Obtain poolId from log
        id: obtain-poolid
        run: |
          echo "poolid=$(tail -1 ${{ secrets.REPO_NAME_GITOPS }}/${{ env.namespace }}/log/schedule-deployments.jsonl \
            | jq -r '.poolId')" | tee -a "$GITHUB_OUTPUT"

      - name: Show schedule summary
        run: |
          if ${{ inputs.action == 'add' }}; then
            echo "schedule: ${{ inputs.action }}: ${{ steps.verify-inputs.outputs.schedule }}" >> "$GITHUB_STEP_SUMMARY"
          fi
          echo "${{ inputs.action }} pool descriptor: ${{ steps.obtain-poolid.outputs.poolid }}.yaml" >> "$GITHUB_STEP_SUMMARY"

      - name: List pool descriptors
        run: |
          cd ${{ secrets.REPO_NAME_GITOPS }}
          git ls-tree -r --name-only HEAD ${{ env.namespace }}/pools
          cd ..

      - name: Delete pool descriptor if action=remove
        if: ${{ inputs.action == 'remove' }}
        run: |
          cd ${{ secrets.REPO_NAME_GITOPS }}
          filename="${{ env.namespace }}/pools/${{ steps.obtain-poolid.outputs.poolid }}.yaml"
          if [ -e "${filename}" ]; then
            git rm "${filename}"
          else
            echo "The pool descriptor '${filename}' does not exist."
          fi
          cd ..

      - name: Commit git changes and push
        run: |
          cd ${{ secrets.REPO_NAME_GITOPS }}
          git config --global user.name "github-actions-reservoir-scripts"
          git config --global user.email "github-actions-reservoir-scripts@indexdata.com"
          git add .
          git status
          if ${{ inputs.action == 'add' }}; then
            git commit -m "Add pool ${{ steps.obtain-poolid.outputs.poolid }}"
          else
            git commit -m "Remove pool ${{ steps.obtain-poolid.outputs.poolid }}"
          fi
          echo "Do git push ..."
          git push

      - name: Show recent schedule
        run: tail -5 ${{ secrets.REPO_NAME_GITOPS }}/${{ env.namespace }}/log/schedule-deployments.jsonl
